schema_version: 1
repositories:
  - name: burro
    path: /Volumes/code/yaup/repos/burro
    remote: 'git@github.com:erme2/Burro.git'
  - name: coffee-brews
    path: /Volumes/code/yaup/repos/coffee-brews
    remote: 'git@github.com:erme2/coffee-brews.git'
  - name: leazy
    path: /Volumes/code/yaup/repos/leazy
    remote: 'git@github.com:erme2/leazy.git'
  - name: pane
    path: /Volumes/code/yaup/repos/pane
    remote: 'git@github.com:erme2/pane.git'
