schema_version: 1
repositories:
  - name: coffee-brews
    path: /Volumes/code/yaup/repos/coffee-brews
    remote: 'git@github.com:erme2/coffee-brews.git'
  - name: leazy
    path: /Volumes/code/yaup/repos/leazy
    remote: 'git@github.com:erme2/leazy.git'
  - name: pane
    path: /Volumes/code/yaup/repos/pane
    remote: 'git@github.com:erme2/pane.git'
  - name: latte
    path: /Volumes/code/yaup/repos/Latte
    remote: 'git@github.com:erme2/Latte.git'
  - name: erme2.com
    path: /Volumes/code/yaup/repos/erme2.com
    remote: 'git@github.com:erme2/erme2.com.git'
